This Lab is based on the Text mining  and NLP Course

## Lab 1.  Data analysis with pandas

# Table of Contents
<ol start="0">
<li> Learning Goals </li>
<li> Loading and Cleaning with Pandas</li>
<li> Parsing and Completing the Dataframe  </li>
<li> Grouping </li>
</ol>

## Learning Goals

About 6000 odd "best books" were fetched and parsed from [Goodreads](https://www.goodreads.com). The "bestness" of these books came from a proprietary formula used by Goodreads and published as a list on their web site.

We parsed the page for each book and saved data from all these pages in a tabular format as a CSV file. In this lab we'll clean and further parse the data.  We'll then do some exploratory data analysis to answer questions about these best books and popular genres.  


By the end of this lab, you should be able to:

- Load and systematically address missing values, for example, by removing observations associated with these values.
- Parse columns in the dataframe to create new dataframe columns.
- Use groupby to aggregate data on a particular feature column, such as author.

Explanation:

Step 1: Loading and Handling Missing Data


When we load the dataset, some information might be missing. These missing values are marked as NaN (Not a Number).
We'll first look at these missing values, and then decide if we should remove those rows or fill in the gaps with something else.

Step 2: Parsing Data Columns


Sometimes, the data we have can be split into more detailed parts. For example, if we have a column that combines an author's full name, we might split it into "First Name" and "Last Name."
This process is called parsing, and it helps us get more specific information from our data.

Step 3: Grouping and Aggregating Data


Grouping data means organizing it based on a shared feature. For example, we can group all books by the same author.
After grouping, we can summarize the data to answer questions like, "Which author has the most books on the list?" or "Which genre is most popular?"

### Basic EDA workflow


The basic workflow is as follows:

1. **Build** a DataFrame from the data (ideally, put all data in this object)
2. **Clean** the DataFrame. It should have the following properties:
    - Each row describes a single object
    - Each column describes a property of that object
    - Columns are numeric whenever appropriate
    - Columns contain atomic properties that cannot be further decomposed
3. Explore **global properties**. Use histograms, scatter plots, and aggregation functions to summarize the data.
4. Explore **group properties**. Use groupby and small multiples to compare subsets of the data.

This process transforms your data into a format which is easier to work with, gives you a basic overview of the data's properties, and likely generates several questions for you to followup in subsequent analysis.

## Part 1: Loading and Cleaning with Pandas
Read in the `goodreads.csv` file, examine the data, and do any necessary data cleaning.

Here is a description of the columns (in order) present in this csv file:

```
rating: the average rating on a 1-5 scale achieved by the book
review_count: the number of Goodreads users who reviewed this book
isbn: the ISBN code for the book
booktype: an internal Goodreads identifier for the book
author_url: the Goodreads (relative) URL for the author of the book
year: the year the book was published
genre_urls: a string with '|' separated relative URLS of Goodreads genre pages
dir: a directory identifier internal to the scraping code
rating_count: the number of ratings for this book (this is different from the number of reviews)
name: the name of the book
```

Let us see what issues we find with the data and resolve them.  



----




After loading appropriate libraries

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
pd.set_option('display.width', 500)
pd.set_option('display.max_columns', 100)

### Cleaning: Reading in the data
We read in and clean the data from `goodreads.csv`.

In [5]:
#Read the data into a dataframe
df = pd.read_csv("/content/drive/MyDrive/NLP_Labs/goodreads.csv")

#Examine the first few rows of the dataframe
df.head()

   4.40   136455  0439023483  good_reads:book https://www.goodreads.com/author/show/153394.Suzanne_Collins    2008 /genres/young-adult|/genres/science-fiction|/genres/dystopia|/genres/fantasy|/genres/science-fiction|/genres/romance|/genres/adventure|/genres/book-club|/genres/young-adult|/genres/teen|/genres/apocalyptic|/genres/post-apocalyptic|/genres/action                dir01/2767052-the-hunger-games.html    2958974            The Hunger Games (The Hunger Games, #1)
0  4.41  16648.0  0439358078  good_reads:book  https://www.goodreads.com/author/show/1077326....            2003.0  /genres/fantasy|/genres/young-adult|/genres/fi...                                                                                                                                                                                                     dir01/2.Harry_Potter_and_the_Order_of_the_Phoe...  1284478.0  Harry Potter and the Order of the Phoenix (Har...
1  3.56  85746.0  0316015849  good_reads:book  https://www.goodreads.com/author/show/941441.S...            2005.0  /genres/young-adult|/genres/fantasy|/genres/ro...                                                                                                                                                                                                                             dir01/41865.Twilight.html  2579564.0                            Twilight (Twilight, #1)
2  4.23  47906.0  0061120081  good_reads:book  https://www.goodreads.com/author/show/1825.Har...            1960.0  /genres/classics|/genres/fiction|/genres/histo...                                                                                                                                                                                                                 dir01/2657.To_Kill_a_Mockingbird.html  2078123.0                              To Kill a Mockingbird
3  4.23  34772.0  0679783261  good_reads:book  https://www.goodreads.com/author/show/1265.Jan...            1813.0  /genres/classics|/genres/fiction|/genres/roman...                                                                                                                                                                                                                   dir01/1885.Pride_and_Prejudice.html  1388992.0                                Pride and Prejudice
4  4.25  12363.0  0446675539  good_reads:book  https://www.goodreads.com/author/show/11081.Ma...            1936.0  /genres/classics|/genres/historical-fiction|/g...                                                                                                                                                                                                                   dir01/18405.Gone_with_the_Wind.html   645470.0                                 Gone with the Wind

Oh dear. That does not quite seem to be right. We are missing the column names. We need to add these in! But what are they?

Here is a list of them in order:

`["rating", 'review_count', 'isbn', 'booktype','author_url', 'year', 'genre_urls', 'dir','rating_count', 'name']`

<div class="exercise"><b>Exercise</b></div>
Use these to load the dataframe properly! And then "head" the dataframe... (you will need to look at the read_csv docs)

In [6]:
# your code here

df.columns = ["rating", 'review_count', 'isbn', 'booktype','author_url', 'year', 'genre_urls', 'dir','rating_count', 'name']
df.head()

   rating  review_count        isbn         booktype                                         author_url    year                                         genre_urls                                                dir  rating_count                                               name
0    4.41       16648.0  0439358078  good_reads:book  https://www.goodreads.com/author/show/1077326....  2003.0  /genres/fantasy|/genres/young-adult|/genres/fi...  dir01/2.Harry_Potter_and_the_Order_of_the_Phoe...     1284478.0  Harry Potter and the Order of the Phoenix (Har...
1    3.56       85746.0  0316015849  good_reads:book  https://www.goodreads.com/author/show/941441.S...  2005.0  /genres/young-adult|/genres/fantasy|/genres/ro...                          dir01/41865.Twilight.html     2579564.0                            Twilight (Twilight, #1)
2    4.23       47906.0  0061120081  good_reads:book  https://www.goodreads.com/author/show/1825.Har...  1960.0  /genres/classics|/genres/fiction|/genres/histo...              dir01/2657.To_Kill_a_Mockingbird.html     2078123.0                              To Kill a Mockingbird
3    4.23       34772.0  0679783261  good_reads:book  https://www.goodreads.com/author/show/1265.Jan...  1813.0  /genres/classics|/genres/fiction|/genres/roman...                dir01/1885.Pride_and_Prejudice.html     1388992.0                                Pride and Prejudice
4    4.25       12363.0  0446675539  good_reads:book  https://www.goodreads.com/author/show/11081.Ma...  1936.0  /genres/classics|/genres/historical-fiction|/g...                dir01/18405.Gone_with_the_Wind.html      645470.0                                 Gone with the Wind

### Cleaning: Examing the dataframe - quick checks

We should examine the dataframe to get a overall sense of the content.

<div class="exercise"><b>Exercise</b></div>
Lets check the types of the columns. What do you find?

In [7]:
# your code here

df.dtypes

rating          float64
review_count    float64
isbn             object
booktype         object
author_url       object
year            float64
genre_urls       object
dir              object
rating_count    float64
name             object
dtype: object



There are numircal and non-numerical datatypes

There are a couple more quick sanity checks to perform on the dataframe.

In [8]:

print(df.shape)
df.columns

(5999, 10)

Index(['rating', 'review_count', 'isbn', 'booktype', 'author_url', 'year', 'genre_urls', 'dir', 'rating_count', 'name'], dtype='object')

### Cleaning: Examining the dataframe - a deeper look

Beyond performing checking some quick general properties of the data frame and looking at the first $n$ rows, we can dig a bit deeper into the values being stored. If you haven't already, check to see if there are any missing values in the data frame.

Let's see for a column which seemed OK to us.

In [9]:
#Get a sense of how many missing values there are in the dataframe. Do it for all columns
np.sum([df.rating.isnull()])

np.int64(2)

In [10]:
#Try to locate where the missing values occur
df[df.rating.isnull()]

      rating  review_count isbn booktype author_url  year genre_urls                              dir  rating_count name
3642     NaN           NaN  NaN      NaN        NaN   NaN        NaN  dir37/9658936-harry-potter.html           NaN  NaN
5281     NaN           NaN  NaN      NaN        NaN   NaN        NaN     dir53/113138.The_Winner.html           NaN  NaN

In [11]:
# For all at once
df.isnull().sum()

rating            2
review_count      2
isbn            477
booktype          2
author_url        2
year              7
genre_urls       62
dir               0
rating_count      2
name              2
dtype: int64

How does `pandas` or `numpy` handle missing values when we try to compute with data sets that include them?

We'll now check if any of the other suspicious columns have missing values.  Let's look at `year` and `review_count` first.

One thing you can do is to try and convert to the type you expect the column to be. If something goes wrong, it likely means your data are bad.

Lets test for missing data:

In [12]:
df[df.year.isnull()]

      rating  review_count        isbn         booktype                                         author_url  year                                         genre_urls                                                dir  rating_count                                               name
2441    4.23         526.0         NaN  good_reads:book  https://www.goodreads.com/author/show/623606.A...   NaN  /genres/religion|/genres/islam|/genres/non-fic...                       dir25/1301625.La_Tahzan.html        4134.0                                          La Tahzan
2868    4.61           2.0         NaN  good_reads:book  https://www.goodreads.com/author/show/8182217....   NaN                                                NaN  dir29/22031070-my-death-experiences---a-preach...          23.0  My Death Experiences - A Preacherâs 18 Apoca...
3642     NaN           NaN         NaN              NaN                                                NaN   NaN                                                NaN                    dir37/9658936-harry-potter.html           NaN                                                NaN
5281     NaN           NaN         NaN              NaN                                                NaN   NaN                                                NaN                       dir53/113138.The_Winner.html           NaN                                                NaN
5571    3.71          35.0  8423336603  good_reads:book  https://www.goodreads.com/author/show/285658.E...   NaN                                    /genres/fiction  dir56/890680._rase_una_vez_el_amor_pero_tuve_q...         403.0  Ãrase una vez el amor pero tuve que matarlo. ...
5657    4.32          44.0         NaN  good_reads:book  https://www.goodreads.com/author/show/25307.Ro...   NaN  /genres/fantasy|/genres/fantasy|/genres/epic-f...  dir57/5533041-assassin-s-apprentice-royal-assa...        3850.0  Assassin's Apprentice / Royal Assassin (Farsee...
5682    4.56         204.0         NaN  good_reads:book  https://www.goodreads.com/author/show/3097905....   NaN  /genres/fantasy|/genres/young-adult|/genres/ro...                  dir57/12474623-tiger-s-dream.html         895.0                 Tiger's Dream (The Tiger Saga, #5)

### Cleaning: Dealing with Missing Values
How should we interpret 'missing' or 'invalid' values in the data (hint: look at where these values occur)? One approach is to simply exclude them from the dataframe. Is this appropriate for all 'missing' or 'invalid' values?

In [13]:
#Treat the missing or invalid values in your dataframe
#######

df = df[df.year.notnull()]

Ok so we have done some cleaning. What do things look like now? Notice the float has not yet changed.

In [14]:
df.dtypes

rating          float64
review_count    float64
isbn             object
booktype         object
author_url       object
year            float64
genre_urls       object
dir              object
rating_count    float64
name             object
dtype: object

In [15]:
df.isnull().sum()

rating            0
review_count      0
isbn            471
booktype          0
author_url        0
year              0
genre_urls       59
dir               0
rating_count      0
name              0
dtype: int64

In [16]:
print(np.sum(df.year.isnull()))
print(np.sum(df.rating_count.isnull()))
print(np.sum(df.review_count.isnull()))
# We removed seven rows
df.shape

0
0
0

(5992, 10)

*Suspect observations for rating and rating_count were removed as well! *

<div class="exercise"><b>Exercise</b></div>

Ok so lets fix those types. Convert them to ints. If the type conversion fails, we now know we have further problems.

In [17]:
# your code here
df = df.astype({'rating': int, 'author_url': 'string', 'rating_count': int, 'year': int, 'name': 'string', 'review_count': int})

Once you do this, we seem to be good on these columns (no errors in conversion). Lets look:

In [18]:
df.dtypes

rating                   int64
review_count             int64
isbn                    object
booktype                object
author_url      string[python]
year                     int64
genre_urls              object
dir                     object
rating_count             int64
name            string[python]
dtype: object

Sweet!

Some of the other colums that should be strings have NaN.

In [19]:
df.loc[df.genre_urls.isnull(), 'genre_urls']=""
df.loc[df.isbn.isnull(), 'isbn']=""

##  Part 2: Parsing and Completing the Data Frame

We will parse the `author` column from the author_url and `genres` column from the genre_urls. Keep the `genres` column as a string separated by '|'.

We will use panda's `map` to assign new columns to the dataframe.

Examine an example `author_url` and reason about which sequence of string operations must be performed in order to isolate the author's name.

In [20]:
#Get the first author_url
test_string = df.author_url[0]
test_string

'https://www.goodreads.com/author/show/1077326.J_K_Rowling'

In [21]:
#Test out some string operations to isolate the author name

test_string.split('/')[-1].split('.')[1:][0]

'J_K_Rowling'

<div class="exercise"><b>Exercise</b></div>

Lets wrap the above code into a function which we will then use

In [22]:
# Write a function that accepts an author url and returns the author's name based on your experimentation above
def get_author(url):
    # your code here
    try:
        return url.split('/')[-1].split('.')[1]
    except IndexError:
        return None

In [23]:
#Apply the get_author function to the 'author_url' column using '.map'
#and add a new column 'author' to store the names
df['author'] = df.author_url.map(get_author)
df.author[0:5]

0          J_K_Rowling
1      Stephenie_Meyer
2           Harper_Lee
3          Jane_Austen
4    Margaret_Mitchell
Name: author, dtype: object

<div class="exercise"><b>Exercise</b></div>

Now parse out the genres from `genre_url`.  

This is a little more complicated because there be more than one genre.

In [24]:

df.genre_urls.head()

0    /genres/fantasy|/genres/young-adult|/genres/fi...
1    /genres/young-adult|/genres/fantasy|/genres/ro...
2    /genres/classics|/genres/fiction|/genres/histo...
3    /genres/classics|/genres/fiction|/genres/roman...
4    /genres/classics|/genres/historical-fiction|/g...
Name: genre_urls, dtype: object

In [25]:
# your code here

def get_genres(url):
    try:
        # split on "|" to separate genres
        genres = url.strip().split('|')
        # get the last part after "/"
        genres = [g.split('/')[-1] for g in genres if g]
        return "|".join(genres)
    except:
        return None


#Test out some string operations to isolate the genre name
test_genre_string=df.genre_urls[0]
genres=test_genre_string.strip().split('|')
for e in genres:
    print(e.split('/')[-1])
    "|".join(genres)

fantasy
young-adult
fiction
fantasy
magic
childrens
adventure
science-fiction-fantasy

In [26]:
get_genres(df.genre_urls[0])

'fantasy|young-adult|fiction|fantasy|magic|childrens|adventure|science-fiction-fantasy'

<div class="exercise"><b>Exercise</b></div>

Write a function that accepts a genre url and returns the genre name based on your experimentation above

In [27]:
def split_and_join_genres(url):
    # your code here
    try:
        genres = url.strip().split('|')
        genres = [g.split('/')[-1] for g in genres if g]
        return "|".join(genres)
    except:
        return None

Test your function

In [28]:
split_and_join_genres("/genres/young-adult|/genres/science-fiction")

'young-adult|science-fiction'

In [29]:
split_and_join_genres("")

''

<div class="exercise"><b>Exercise</b></div>

Use map again to create a new "genres" column

In [30]:

df['genres']=df.genre_urls.map(split_and_join_genres)
df.head()

   rating  review_count        isbn         booktype                                         author_url  year                                         genre_urls                                                dir  rating_count                                               name             author                                             genres
0       4         16648  0439358078  good_reads:book  https://www.goodreads.com/author/show/1077326....  2003  /genres/fantasy|/genres/young-adult|/genres/fi...  dir01/2.Harry_Potter_and_the_Order_of_the_Phoe...       1284478  Harry Potter and the Order of the Phoenix (Har...        J_K_Rowling  fantasy|young-adult|fiction|fantasy|magic|chil...
1       3         85746  0316015849  good_reads:book  https://www.goodreads.com/author/show/941441.S...  2005  /genres/young-adult|/genres/fantasy|/genres/ro...                          dir01/41865.Twilight.html       2579564                            Twilight (Twilight, #1)    Stephenie_Meyer  young-adult|fantasy|romance|paranormal|vampire...
2       4         47906  0061120081  good_reads:book  https://www.goodreads.com/author/show/1825.Har...  1960  /genres/classics|/genres/fiction|/genres/histo...              dir01/2657.To_Kill_a_Mockingbird.html       2078123                              To Kill a Mockingbird         Harper_Lee  classics|fiction|historical-fiction|academic|s...
3       4         34772  0679783261  good_reads:book  https://www.goodreads.com/author/show/1265.Jan...  1813  /genres/classics|/genres/fiction|/genres/roman...                dir01/1885.Pride_and_Prejudice.html       1388992                                Pride and Prejudice        Jane_Austen  classics|fiction|romance|historical-fiction|li...
4       4         12363  0446675539  good_reads:book  https://www.goodreads.com/author/show/11081.Ma...  1936  /genres/classics|/genres/historical-fiction|/g...                dir01/18405.Gone_with_the_Wind.html        645470                                 Gone with the Wind  Margaret_Mitchell  classics|historical-fiction|fiction|romance|li...

Finally, let's pick an author at random so we can see the results of the transformations.  Scroll to see the `author` and `genre` columns that we added to the dataframe.

In [31]:
df[df.author == "Marguerite_Yourcenar"]

      rating  review_count        isbn         booktype                                         author_url  year                                         genre_urls                                  dir  rating_count                name                author                                             genres
1013       4           483  0374529264  good_reads:book  https://www.goodreads.com/author/show/7732.Mar...  1951  /genres/historical-fiction|/genres/fiction|/ge...  dir11/12172.Memoirs_of_Hadrian.html          6258  Memoirs of Hadrian  Marguerite_Yourcenar  historical-fiction|fiction|cultural|france|cla...
5619       4            74  2070367983  good_reads:book  https://www.goodreads.com/author/show/7732.Mar...  1968  /genres/fiction|/genres/historical-fiction|/ge...     dir57/953435.L_uvre_au_noir.html          1601    L'Åuvre au noir  Marguerite_Yourcenar  fiction|historical-fiction|cultural|france|eur...

Let us delete the `genre_urls` column.

In [32]:
del df['genre_urls']

And then save the dataframe out!

In [34]:
df.to_csv("/content/drive/MyDrive/NLP_Labs/cleaned-goodreads.csv", index=False, header=True)

---

## Part 3: Grouping

It appears that some books were written in negative years!  Print out the observations that correspond to negative years.  What do you notice about these books?

In [35]:
# your code here

print(df[df['year'] < 0])

      rating  review_count        isbn         booktype                                         author_url  year                                                dir  rating_count                                  name        author                                             genres
46         3          5785  0143039954  good_reads:book    https://www.goodreads.com/author/show/903.Homer  -800                        dir01/1381.The_Odyssey.html        560248                           The Odyssey         Homer  classics|fiction|poetry|fantasy|mythology|acad...
245        4           365  0147712556  good_reads:book    https://www.goodreads.com/author/show/903.Homer  -800              dir03/1375.The_Iliad_The_Odyssey.html         35123                 The Iliad/The Odyssey         Homer  classics|fantasy|mythology|fantasy|academic|sc...
454        3          1499  0140449140  good_reads:book    https://www.goodreads.com/author/show/879.Plato  -380                      dir05/30289.The_Republic.html         82022                          The Republic         Plato  philosophy|classics|non-fiction|politics|histo...
595        3          1240  0679729526  good_reads:book   https://www.goodreads.com/author/show/919.Virgil   -29                        dir06/12914.The_Aeneid.html         60308                            The Aeneid        Virgil  classics|poetry|fiction|fantasy|mythology|acad...
628        3          1231  1580495931  good_reads:book  https://www.goodreads.com/author/show/1002.Sop...  -429                        dir07/1554.Oedipus_Rex.html         93192                           Oedipus Rex     Sophocles  classics|plays|drama|fiction|academic|school|l...
673        3          3559  1590302257  good_reads:book  https://www.goodreads.com/author/show/1771.Sun...  -512                    dir07/10534.The_Art_of_War.html        114619                        The Art of War       Sun_Tzu  non-fiction|politics|classics|literature|psych...
745        4          1087  0140449183  good_reads:book  https://www.goodreads.com/author/show/5158478....  -500                 dir08/99944.The_Bhagavad_Gita.html         31634                     The Bhagavad Gita     Anonymous  classics|spirituality|religion|hinduism|fantas...
776        3          1038  1580493882  good_reads:book  https://www.goodreads.com/author/show/1002.Sop...  -442                           dir08/7728.Antigone.html         49084                              Antigone     Sophocles  drama|fiction|classics|academic|read-for-schoo...
1232       3           704  015602764X  good_reads:book  https://www.goodreads.com/author/show/1002.Sop...  -400                  dir13/1540.The_Oedipus_Cycle.html         36008                     The Oedipus Cycle     Sophocles  classics|plays|drama|fiction|literature|academ...
1396       4           890  0192840509  good_reads:book  https://www.goodreads.com/author/show/12452.Aesop  -560                    dir14/21348.Aesop_s_Fables.html         71259                        Aesop's Fables         Aesop  classics|childrens|literature|fantasy|fairy-ta...
1397       3          1644  0141026286  good_reads:book  https://www.goodreads.com/author/show/5158478.... -1500             dir14/19351.The_Epic_of_Gilgamesh.html         42026                 The Epic of Gilgamesh     Anonymous  religion|literature|ancient|academic|read-for-...
1427       3           539  0486275485  good_reads:book  https://www.goodreads.com/author/show/973.Euri...  -431                            dir15/752900.Medea.html         29858                                 Medea     Euripides  classics|plays|drama|fiction|fantasy|mythology...
1814       3           493  0140443339  good_reads:book  https://www.goodreads.com/author/show/990.Aesc...  -458                       dir19/1519.The_Oresteia.html         18729                          The Oresteia     Aeschylus  classics|plays|drama|fiction|fantasy|mythology...
1881       4           377  0872205541  good_reads:book    https://www.goodreads.com/author/show/879.Plato  -400   dir19/22632.The_Trial_and_Death_of_Socrates.html         18712       The Trial and Death of Socrates         Plato  philosophy|classics|non-fiction|history|litera...
2077       3           399  0140440399  good_reads:book  https://www.goodreads.com/author/show/957.Thuc...  -411  dir21/261243.The_History_of_the_Peloponnesian_...         17212  The History of the Peloponnesian War    Thucydides  history|classics|non-fiction|war|war|military|...
2526       3           506  0140449086  good_reads:book  https://www.goodreads.com/author/show/901.Hero...  -440                      dir26/1362.The_Histories.html         20570                         The Histories     Herodotus  history|classics|non-fiction|cultural|greece|l...
3132       4           131  0872203492  good_reads:book    https://www.goodreads.com/author/show/879.Plato  -400                     dir32/9462.Complete_Works.html          7454                        Complete Works         Plato  philosophy|classics|non-fiction|history|litera...
3273       3           411  0140449493  good_reads:book  https://www.goodreads.com/author/show/2192.Ari...  -350            dir33/19068.The_Nicomachean_Ethics.html         16534                The Nicomachean Ethics     Aristotle  philosophy|classics|non-fiction|politics|acade...
3756       3           364  0872206033  good_reads:book  https://www.goodreads.com/author/show/1011.Ari...  -411                         dir38/1591.Lysistrata.html         18070                            Lysistrata  Aristophanes  plays|classics|drama|fiction|plays|theatre|hum...
4401       3           516  0140449272  good_reads:book    https://www.goodreads.com/author/show/879.Plato  -370                     dir45/81779.The_Symposium.html         18457                         The Symposium         Plato  non-fiction|classics|philosophy|academic|schoo...
4474       4           281  0865163480  good_reads:book    https://www.goodreads.com/author/show/879.Plato  -390                           dir45/73945.Apology.html         11478                               Apology         Plato  philosophy|classics|non-fiction|history|academ...
5366       4           133  0872206335  good_reads:book    https://www.goodreads.com/author/show/879.Plato  -360                    dir54/30292.Five_Dialogues.html          9964                        Five Dialogues         Plato  philosophy|classics|non-fiction|academic|schoo...

We can determine the "best book" by year! For this we use Pandas groupby. Groupby allows grouping a dataframe by any (usually categorical) variable.

In [36]:
dfgb_author = df.groupby('author')
type(dfgb_author)

pandas.core.groupby.generic.DataFrameGroupBy

Perhaps we want the number of books each author wrote

In [37]:
dfgb_author.count()

                       rating  review_count  isbn  booktype  author_url  year  dir  rating_count  name  genres
author
A_A_Milne                   6             6     6         6           6     6    6             6     6       6
A_G_Howard                  1             1     1         1           1     1    1             1     1       1
A_J_Cronin                  1             1     1         1           1     1    1             1     1       1
A_J_Jacobs                  1             1     1         1           1     1    1             1     1       1
A_J_Salt                    1             1     1         1           1     1    1             1     1       1
...                       ...           ...   ...       ...         ...   ...  ...           ...   ...     ...
_                          42            42    42        42          42    42   42            42    42      42
_gota_Krist_f               1             1     1         1           1     1    1             1     1       1
_mile_Zola                  4             4     4         4           4     4    4             4     4       4
_ric_Emmanuel_Schmitt       1             1     1         1           1     1    1             1     1       1
_sne_Seierstad              1             1     1         1           1     1    1             1     1       1

[2645 rows x 10 columns]

Lots of useless info there. One column should suffice

In [38]:
dfgb_author['author'].count()

author
A_A_Milne                 6
A_G_Howard                1
A_J_Cronin                1
A_J_Jacobs                1
A_J_Salt                  1
                         ..
_                        42
_gota_Krist_f             1
_mile_Zola                4
_ric_Emmanuel_Schmitt     1
_sne_Seierstad            1
Name: author, Length: 2645, dtype: int64

Perhaps you want more detailed info...

In [39]:
dfgb_author[['rating', 'rating_count', 'review_count', 'year']].describe()

                      rating                                              rating_count                                                                             review_count                                                                      year
                       count      mean      std  min   25%  50%  75%  max        count          mean           std      min       25%      50%       75%       max        count         mean          std     min      25%     50%      75%     max count         mean         std     min      25%     50%      75%     max
author
A_A_Milne                6.0  4.000000  0.00000  4.0  4.00  4.0  4.0  4.0          6.0  47842.333333  57135.314010    544.0  15559.50  30547.0  50401.25  157833.0          6.0   543.000000   682.473150     1.0   219.50   309.5   499.25  1886.0   6.0  1944.166667   29.294482  1926.0  1926.25  1927.5  1952.75  1997.0
A_G_Howard               1.0  4.000000      NaN  4.0  4.00  4.0  4.0  4.0          1.0  17073.000000           NaN  17073.0  17073.00  17073.0  17073.00   17073.0          1.0  3194.000000          NaN  3194.0  3194.00  3194.0  3194.00  3194.0   1.0  2013.000000         NaN  2013.0  2013.00  2013.0  2013.00  2013.0
A_J_Cronin               1.0  4.000000      NaN  4.0  4.00  4.0  4.0  4.0          1.0   1015.000000           NaN   1015.0   1015.00   1015.0   1015.00    1015.0          1.0   109.000000          NaN   109.0   109.00   109.0   109.00   109.0   1.0  1941.000000         NaN  1941.0  1941.00  1941.0  1941.00  1941.0
A_J_Jacobs               1.0  3.000000      NaN  3.0  3.00  3.0  3.0  3.0          1.0  39489.000000           NaN  39489.0  39489.00  39489.0  39489.00   39489.0          1.0  4371.000000          NaN  4371.0  4371.00  4371.0  4371.00  4371.0   1.0  2007.000000         NaN  2007.0  2007.00  2007.0  2007.00  2007.0
A_J_Salt                 1.0  4.000000      NaN  4.0  4.00  4.0  4.0  4.0          1.0     16.000000           NaN     16.0     16.00     16.0     16.00      16.0          1.0     6.000000          NaN     6.0     6.00     6.0     6.00     6.0   1.0  2014.000000         NaN  2014.0  2014.00  2014.0  2014.00  2014.0
...                      ...       ...      ...  ...   ...  ...  ...  ...          ...           ...           ...      ...       ...      ...       ...       ...          ...          ...          ...     ...      ...     ...      ...     ...   ...          ...         ...     ...      ...     ...      ...     ...
_                       42.0  3.571429  0.50087  3.0  3.00  4.0  4.0  4.0         42.0  11574.642857   9368.218450     10.0   4724.00   8709.5  15572.75   39302.0         42.0  1437.214286  1216.421371     1.0   534.75  1020.5  1745.75  4785.0  42.0  1998.904762   18.721071  1941.0  1994.75  2007.0  2010.75  2014.0
_gota_Krist_f            1.0  4.000000      NaN  4.0  4.00  4.0  4.0  4.0          1.0   2628.000000           NaN   2628.0   2628.00   2628.0   2628.00    2628.0          1.0   243.000000          NaN   243.0   243.00   243.0   243.00   243.0   1.0  1986.000000         NaN  1986.0  1986.00  1986.0  1986.00  1986.0
_mile_Zola               4.0  3.750000  0.50000  3.0  3.75  4.0  4.0  4.0          4.0   8358.250000   4553.226942   3594.0   5181.75   8095.0  11271.50   13649.0          4.0   283.750000   171.069917   125.0   189.50   243.5   337.75   523.0   4.0  1652.500000  456.345264   968.0  1649.75  1878.5  1881.25  1885.0
_ric_Emmanuel_Schmitt    1.0  4.000000      NaN  4.0  4.00  4.0  4.0  4.0          1.0   6439.000000           NaN   6439.0   6439.00   6439.0   6439.00    6439.0          1.0   424.000000          NaN   424.0   424.00   424.0   424.00   424.0   1.0  2002.000000         NaN  2002.0  2002.00  2002.0  2002.00  2002.0
_sne_Seierstad           1.0  3.000000      NaN  3.0  3.00  3.0  3.0  3.0          1.0  24993.000000           NaN  24993.0  24993.00  24993.0  24993.00   24993.0          1.0  2088.000000          NaN  2088.0  2088.00  2088.0  2088.00  2088.0   1.0  2002.000000         NaN  2002.0  2002.00  2002.0  2002.00  2002.0

[2645 rows x 32 columns]

You can also access a `groupby` dictionary style.

In [40]:
ratingdict = {}
for author, subset in dfgb_author:
    ratingdict[author] = (subset['rating'].mean(), subset['rating'].std())
ratingdict

{'A_A_Milne': (np.float64(4.0), 0.0),
 'A_G_Howard': (np.float64(4.0), nan),
 'A_J_Cronin': (np.float64(4.0), nan),
 'A_J_Jacobs': (np.float64(3.0), nan),
 'A_J_Salt': (np.float64(4.0), nan),
 'A_Meredith_Walters': (np.float64(4.0), 0.0),
 'A_N_Roquelaure': (np.float64(3.0), 0.0),
 'A_S_Byatt': (np.float64(3.0), nan),
 'A_S_King': (np.float64(3.0), nan),
 'A_id_al_Qarni': (np.float64(3.5), 0.7071067811865476),
 'Abbi_Glines': (np.float64(3.857142857142857), 0.3631365196012815),
 'Abdul_Rahman_Munif': (np.float64(4.0), nan),
 'Abigail_Gibbs': (np.float64(3.0), nan),
 'Abigail_Roux': (np.float64(4.0), 0.0),
 'Abigail_Thomas': (np.float64(3.0), nan),
 'Abolqasem_Ferdowsi': (np.float64(4.0), nan),
 'Abraham_Verghese': (np.float64(4.0), nan),
 'Abul_Hasan_Ali_Nadwi': (np.float64(4.0), nan),
 'Adam_Hochschild': (np.float64(4.0), nan),
 'Adam_Johnson': (np.float64(4.0), nan),
 'Adam_Levin': (np.float64(4.0), nan),
 'Adam_Rex': (np.float64(4.0), nan),
 'Adam_Smith': (np.float64(3.0), nan),
 'Addison_Moore': (np.float64(3.0), nan),
 'Adeline_Yen_Mah': (np.float64(4.0), nan),
 'Adolf_Hitler': (np.float64(2.0), nan),
 'Adolfo_Bioy_Casares': (np.float64(4.0), nan),
 'Aeschylus': (np.float64(3.0), nan),
 'Aesop': (np.float64(4.0), nan),
 'Agatha_Christie': (np.float64(3.3636363636363638), 0.504524979109513),
 'Ahlam_Mosteghanemi': (np.float64(3.0), nan),
 'Ahmad_Baari': (np.float64(4.0), nan),
 'Ahmad_Fuadi': (np.float64(4.0), nan),
 'Ai_Yazawa': (np.float64(4.0), nan),
 'Aidan_Chambers': (np.float64(4.0), nan),
 'Aimee_Carter': (np.float64(3.3333333333333335), 0.5773502691896258),
 'Aimee_Friedman': (np.float64(3.0), nan),
 'Alain_Fournier': (np.float64(3.0), nan),
 'Alan_Bradley': (np.float64(3.0), nan),
 'Alan_Brennert': (np.float64(4.0), nan),
 'Alan_Campbell': (np.float64(3.0), nan),
 'Alan_Hollinghurst': (np.float64(3.0), nan),
 'Alan_Lightman': (np.float64(4.0), nan),
 'Alan_Moore': (np.float64(3.8), 0.4472135954999579),
 'Alan_Paton': (np.float64(3.0), nan),
 'Alan_Wilson_Watts': (np.float64(4.0), nan),
 'Alastair_Reynolds': (np.float64(4.0), nan),
 'Albert_Camus': (np.float64(3.6), 0.5477225575051661),
 'Albert_Einstein': (np.float64(4.0), nan),
 'Albert_Espinosa': (np.float64(3.0), nan),
 'Alcoholics_Anonymous': (np.float64(4.0), nan),
 'Aldo_Leopold': (np.float64(4.0), nan),
 'Aldous_Huxley': (np.float64(3.2), 0.44721359549995787),
 'Aleatha_Romig': (np.float64(4.0), 0.0),
 'Alecia_Stone': (np.float64(3.5), 0.7071067811865476),
 'Aleksandr_Solzhenitsyn': (np.float64(3.6666666666666665),
  0.5773502691896258),
 'Alessandro_Baricco': (np.float64(3.6666666666666665), 0.5773502691896258),
 'Alessandro_Manzoni': (np.float64(3.0), nan),
 'Alex_Flinn': (np.float64(3.0), 0.0),
 'Alex_Garland': (np.float64(3.0), 0.0),
 'Alex_Haley': (np.float64(4.0), nan),
 'Alex_Harris': (np.float64(4.0), nan),
 'Alex_Kotlowitz': (np.float64(4.0), nan),
 'Alex_Sanchez': (np.float64(3.0), 0.0),
 'Alexander_Gordon_Smith': (np.float64(4.0), nan),
 'Alexander_Jovy': (np.float64(4.0), nan),
 'Alexander_McCall_Smith': (np.float64(3.0), nan),
 'Alexander_Pushkin': (np.float64(4.0), nan),
 'Alexandra_Adornetto': (np.float64(3.0), 0.0),
 'Alexandra_Bracken': (np.float64(3.6666666666666665), 0.5773502691896258),
 'Alexandra_Fuller': (np.float64(3.0), nan),
 'Alexandra_Ivy': (np.float64(3.5), 0.7071067811865476),
 'Alexandra_Monir': (np.float64(3.0), nan),
 'Alexandra_Potter': (np.float64(3.0), nan),
 'Alexandra_Ripley': (np.float64(3.0), nan),
 'Alexandre_Dumas': (np.float64(4.0), 0.0),
 'Alexandre_Dumas_fils': (np.float64(3.0), nan),
 'Alexei_Maxim_Russell': (np.float64(3.6666666666666665), 0.5773502691896258),
 'Alexis_de_Tocqueville': (np.float64(3.0), nan),
 'Alfred_Bester': (np.float64(4.0), 0.0),
 'Alfred_Lansing': (np.float64(4.0), nan),
 'Alfred_Tennyson': (np.float64(4.0), nan),
 'Ali_Marsman': (np.float64(4.0), nan),
 'Ali_Smith': (np.float64(3.0), nan),
 'Alice_Clayton': (np.float64(4.0), nan),
 'Alice_Hoffman': (np.float64(3.0), 0.0),
 'Alice_Kuipers': (np.float64(3.0), nan),
 'Alice_Schroeder': (np.float64(4.0), nan),
 'Alice_Sebold': (np.float64(3.0), 0.0),
 'Alice_Walker': (np.float64(4.0), 0.0),
 'Alija_Izetbegovi_': (np.float64(4.0), nan),
 'Alison_Bechdel': (np.float64(4.0), nan),
 'Alison_Croggon': (np.float64(3.75), 0.5),
 'Alison_Goodman': (np.float64(4.0), 0.0),
 'Alison_Weir': (np.float64(3.3333333333333335), 0.5773502691896258),
 'Alistair_MacLeod': (np.float64(3.0), nan),
 'Allan_Frewin_Jones': (np.float64(3.5), 0.7071067811865476),
 'Allan_Gurganus': (np.float64(3.0), nan),
 'Allan_Pease': (np.float64(3.0), nan),
 'Allegra_Goodman': (np.float64(3.0), nan),
 'Allen_Ginsberg': (np.float64(4.0), nan),
 'Ally_Carter': (np.float64(3.7777777777777777), 0.4409585518440984),
 'Ally_Condie': (np.float64(3.0), 0.0),
 'Ally_Shields': (np.float64(3.0), nan),
 'Allyse_Near': (np.float64(4.0), nan),
 'Alma_Katsu': (np.float64(3.0), nan),
 'Alyson_Noel': (np.float64(3.1), 0.31622776601683794),
 'Alyxandra_Harvey': (np.float64(3.6666666666666665), 0.5773502691896258),
 'Am_lie_Nothomb': (np.float64(3.0), 0.0),
 'Amanda_E_Alvarez': (np.float64(3.0), nan),
 'Amanda_Hocking': (np.float64(3.625), 0.5175491695067657),
 'Amber_Argyle': (np.float64(3.0), nan),
 'Amber_Lea_Easton': (np.float64(4.0), nan),
 'Ambrose_Bierce': (np.float64(4.0), nan),
 'Amelia_Atwater_Rhodes': (np.float64(3.8333333333333335),
  0.40824829046386296),
 'Amelia_Hutchins': (np.float64(4.0), 0.0),
 'Ami_McKay': (np.float64(3.0), nan),
 'Amin_Maalouf': (np.float64(4.0), nan),
 'Amish_Tripathi': (np.float64(3.0), 0.0),
 'Amitav_Ghosh': (np.float64(3.0), nan),
 'Amor_Towles': (np.float64(3.0), nan),
 'Amy_A_Bartol': (np.float64(4.0), 0.0),
 'Amy_Efaw': (np.float64(3.0), nan),
 'Amy_Harmon': (np.float64(4.0), 0.0),
 'Amy_Hempel': (np.float64(4.0), nan),
 'Amy_Plum': (np.float64(4.0), 0.0),
 'Amy_Tan': (np.float64(3.0), 0.0),
 'Anastacia_Moore': (np.float64(4.0), nan),
 'Anchee_Min': (np.float64(3.0), nan),
 'Andr_Aciman': (np.float64(4.0), nan),
 'Andr_Gide': (np.float64(3.0), nan),
 'Andre_Agassi': (np.float64(4.0), nan),
 'Andre_Dubus_III': (np.float64(3.0), nan),
 'Andrea_Cremer': (np.float64(4.0), 0.0),
 'Andrea_Hirata': (np.float64(3.75), 0.5),
 'Andrea_Levy': (np.float64(3.0), nan),
 'Andrew_Clements': (np.float64(3.0), 0.0),
 'Andrew_Davidson': (np.float64(3.0), nan),
 'Andrew_Klavan': (np.float64(3.5), 0.7071067811865476),
 'Andrew_Smith': (np.float64(4.0), nan),
 'Andrzej_Sapkowski': (np.float64(4.0), 0.0),
 'Andy_Szpuk': (np.float64(4.0), nan),
 'Andy_Weir': (np.float64(4.0), nan),
 'Angel_Sefer': (np.float64(4.0), nan),
 'Angela_Carter': (np.float64(3.5), 0.7071067811865476),
 'Angela_Morrison': (np.float64(4.0), nan),
 'Angelo_Tsanatelis': (np.float64(4.0), 0.0),
 'Angie_Martin': (np.float64(4.0), 0.0),
 'Angie_Sage': (np.float64(3.0), 0.0),
 'Anita_Diamant': (np.float64(4.0), nan),
 'Anita_Shreve': (np.float64(3.0), nan),
 'Ann_Aguirre': (np.float64(3.5), 0.7071067811865476),
 'Ann_Brashares': (np.float64(3.0), 0.0),
 'Ann_Fairbairn': (np.float64(4.0), nan),
 'Ann_M_Martin': (np.float64(4.0), nan),
 'Ann_Marie_MacDonald': (np.float64(3.0), nan),
 'Ann_Patchett': (np.float64(3.0), 0.0),
 'Ann_Rule': (np.float64(3.6), 0.5477225575051661),
 'Anna_Banks': (np.float64(4.0), 0.0),
 'Anna_Carey': (np.float64(3.0), 0.0),
 'Anna_Gavalda': (np.float64(4.0), nan),
 'Anna_Godbersen': (np.float64(3.0), 0.0),
 'Anna_Lee_Waldo': (np.float64(4.0), nan),
 'Anna_Quindlen': (np.float64(3.0), nan),
 'Anna_Sewell': (np.float64(3.0), nan),
 'Anne_Bishop': (np.float64(3.9), 0.31622776601683794),
 'Anne_Bront_': (np.float64(3.0), 0.0),
 'Anne_Carson': (np.float64(4.0), nan),
 'Anne_Elisabeth_Stengl': (np.float64(3.6666666666666665), 0.5773502691896258),
 'Anne_Fadiman': (np.float64(4.0), nan),
 'Anne_Fortier': (np.float64(3.0), nan),
 'Anne_Frank': (np.float64(4.0), nan),
 'Anne_Lamott': (np.float64(4.0), 0.0),
 'Anne_McCaffrey': (np.float64(3.769230769230769), 0.4385290096535146),
 'Anne_Michaels': (np.float64(3.0), nan),
 'Anne_Morrow_Lindbergh': (np.float64(4.0), nan),
 'Anne_Rice': (np.float64(3.1578947368421053), 0.37463432463267754),
 'Anne_Tyler': (np.float64(3.1666666666666665), 0.40824829046386296),
 'Annemarie_Selinko': (np.float64(3.0), nan),
 'Annette_Curtis_Klause': (np.float64(3.0), 0.0),
 'Annie_Dillard': (np.float64(3.5), 0.7071067811865476),
 'Annie_Proulx': (np.float64(3.0), 0.0),
 'Anonymous': (np.float64(3.823529411764706), 0.3929526239966879),
 'Anthony_Bourdain': (np.float64(3.0), nan),
 'Anthony_Burgess': (np.float64(3.5), 0.7071067811865476),
 'Anthony_Doerr': (np.float64(4.0), nan),
 'Anthony_Hope': (np.float64(3.0), nan),
 'Anthony_Horowitz': (np.float64(3.727272727272727), 0.4670993664969138),
 'Anthony_Kiedis': (np.float64(4.0), nan),
 'Anthony_Marra': (np.float64(4.0), nan),
 'Anthony_Ryan': (np.float64(4.0), nan),
 'Anthony_Swofford': (np.float64(3.0), nan),
 'Anthony_Trollope': (np.float64(3.5), 0.7071067811865476),
 'Antoine_de_Saint_Exup_ry': (np.float64(4.0), 0.0),
 'Anton_Chekhov': (np.float64(3.6666666666666665), 0.5773502691896258),
 'Antonia_Fraser': (np.float64(3.0), nan),
 'Antonia_Michaelis': (np.float64(4.0), nan),
 'Antony_Beevor': (np.float64(4.0), nan),
 'Anya_Seton': (np.float64(4.0), nan),
 'Aporva_Kala': (np.float64(4.0), 0.0),
 'April_Henry': (np.float64(3.0), nan),
 'Aprilynne_Pike': (np.float64(3.5), 0.5773502691896257),
 'Aravind_Adiga': (np.float64(3.0), nan),
 'Ariana_Franklin': (np.float64(3.0), nan),
 'Aristophanes': (np.float64(3.0), nan),
 'Aristotle': (np.float64(3.0), nan),
 'Arkady_Strugatsky': (np.float64(4.0), 0.0),
 'Armando_Cosani': (np.float64(4.0), nan),
 'Armistead_Maupin': (np.float64(4.0), nan),
 'Art_Spiegelman': (np.float64(4.0), 0.0),
 'Arthur_C_Clarke': (np.float64(3.8), 0.4472135954999579),
 'Arthur_Conan_Doyle': (np.float64(3.769230769230769), 0.4385290096535146),
 'Arthur_Golden': (np.float64(4.0), nan),
 'Arthur_Koestler': (np.float64(4.0), nan),
 'Arthur_Miller': (np.float64(3.0), 0.0),
 'Arthur_Ransome': (np.float64(3.0), nan),
 'Arthur_Rimbaud': (np.float64(4.0), 0.0),
 'Arthur_Schnitzler': (np.float64(3.0), nan),
 'Arturo_P_rez_Reverte': (np.float64(3.0), 0.0),
 'Arun_Tiwari': (np.float64(4.0), nan),
 'Arundhati_Roy': (np.float64(3.0), nan),
 'Asa_Don_Brown': (np.float64(4.0), nan),
 'Ashley_Chappell': (np.float64(4.0), 0.0),
 'Ashley_Waelti': (np.float64(4.0), nan),
 'Astrid_Lindgren': (np.float64(4.0), 0.0),
 'Audrey_Niffenegger': (np.float64(3.0), 0.0),
 'Augusten_Burroughs': (np.float64(3.0), 0.0),
 'Augustine_of_Hippo': (np.float64(3.0), nan),
 'Aurora_Rose_Reynolds': (np.float64(4.0), nan),
 'Austin_Kleon': (np.float64(3.0), nan),
 'Author_Neva_Squires_Rodriguez': (np.float64(4.0), nan),
 'Autumn_Cornwell': (np.float64(3.0), nan),
 'Avery_Aster': (np.float64(3.25), 0.5),
 'Avi': (np.float64(3.0), nan),
 'Ayaan_Hirsi_Ali': (np.float64(4.0), nan),
 'Ayn_Rand': (np.float64(3.2), 0.4472135954999579),
 'Azar_Nafisi': (np.float64(3.0), nan),
 'B_Kristin_McMichael': (np.float64(3.3333333333333335), 0.5773502691896258),
 'Banana_Yoshimoto': (np.float64(3.0), nan),
 'Barack_Obama': (np.float64(3.0), nan),
 'Barbara_Demick': (np.float64(4.0), nan),
 'Barbara_Ehrenreich': (np.float64(3.0), nan),
 'Barbara_Erskine': (np.float64(4.0), nan),
 'Barbara_Kingsolver': (np.float64(3.3333333333333335), 0.5163977794943222),
 'Barbara_Taylor_Bradford': (np.float64(4.0), nan),
 'Barbara_W_Tuchman': (np.float64(4.0), 0.0),
 'Barry_Jordan_Jr_': (np.float64(4.0), nan),
 'Barry_Lyga': (np.float64(3.0), nan),
 'Barry_Unsworth': (np.float64(4.0), nan),
 'Beatrice_Sparks': (np.float64(3.0), nan),
 'Beatrix_Potter': (np.float64(4.0), 0.0),
 'Becca_Fitzpatrick': (np.float64(4.0), 0.0),
 'Belle_Aurora': (np.float64(4.0), 0.0),
 'Belsebuub': (np.float64(4.0), nan),
 'Belzebuub': (np.float64(4.0), 0.0),
 'Ben_Goldacre': (np.float64(4.0), nan),
 'Ben_Peller': (np.float64(4.0), 0.0),
 'Ben_Sherwood': (np.float64(3.0), nan),
 'Benedict_Freedman': (np.float64(4.0), nan),
 'Benjamin_Alire_S_enz': (np.float64(4.0), nan),
 'Benjamin_Franklin': (np.float64(3.0), nan),
 'Benjamin_Graham': (np.float64(4.0), nan),
 'Benjamin_Hoff': (np.float64(4.0), 0.0),
 'Bernadette_Azizi': (np.float64(4.0), nan),
 'Bernard_Cornwell': (np.float64(3.888888888888889), 0.33333333333333337),
 'Bernard_Malamud': (np.float64(3.0), 0.0),
 'Bernhard_Schlink': (np.float64(3.0), nan),
 'Bertolt_Brecht': (np.float64(3.0), nan),
 'Bertrand_Russell': (np.float64(4.0), nan),
 'Beryl_Markham': (np.float64(4.0), nan),
 'Bess_Streeter_Aldrich': (np.float64(4.0), nan),
 'Beth_Fantaskey': (np.float64(3.0), nan),
 'Beth_Hoffman': (np.float64(3.0), nan),
 'Beth_Revis': (np.float64(3.5), 0.7071067811865476),
 'Bethany_Hamilton': (np.float64(4.0), nan),
 'Bette_Greene': (np.float64(3.0), nan),
 'Betty_Edwards': (np.float64(3.0), nan),
 'Betty_Friedan': (np.float64(3.0), nan),
 'Betty_MacDonald': (np.float64(4.0), nan),
 'Betty_Mahmoody': (np.float64(3.0), nan),
 'Betty_Smith': (np.float64(4.0), nan),
 'Bev_Stout': (np.float64(4.0), nan),
 'Bill_Bryson': (np.float64(3.3333333333333335), 0.49999999999999994),
 'Bill_Courtney': (np.float64(4.0), nan),
 'Bill_Konigsberg': (np.float64(4.0), nan),
 'Bill_Martin_Jr_': (np.float64(4.0), nan),
 'Bill_Watterson': (np.float64(4.0), 0.0),
 'Billie_Letts': (np.float64(3.0), nan),
 'Bisco_Hatori': (np.float64(4.0), nan),
 'Blue_Jeans': (np.float64(4.0), nan),
 'Bo_Hampton': (np.float64(3.0), nan),
 'Bob_Atkinson': (np.float64(4.0), nan),
 'Bob_Dylan': (np.float64(3.0), nan),
 'Bodie_Thoene': (np.float64(4.0), 0.0),
 'Bohumil_Hrabal': (np.float64(4.0), 0.0),
 'Boris_Pasternak': (np.float64(4.0), nan),
 'Boris_Vian': (np.float64(4.0), 0.0),
 'Brae_Wyckoff': (np.float64(3.0), nan),
 'Bram_Stoker': (np.float64(3.0), nan),
 'Brandon_Mull': (np.float64(4.0), 0.0),
 'Brandon_Sanderson': (np.float64(3.909090909090909), 0.30151134457776363),
 'Bree_Despain': (np.float64(3.5), 0.7071067811865476),
 'Brenna_Yovanoff': (np.float64(3.0), nan),
 'Brent_Weeks': (np.float64(4.0), 0.0),
 'Bret_Easton_Ellis': (np.float64(3.0), 0.0),
 'Brett_Axel': (np.float64(4.0), nan),
 'Brian_Celio': (np.float64(4.0), nan),
 'Brian_Greene': (np.float64(4.0), nan),
 'Brian_Jacques': (np.float64(3.5), 0.5188745216627708),
 'Brian_K_Vaughan': (np.float64(4.0), nan),
 'Brian_Katcher': (np.float64(3.0), nan),
 'Brian_L_Weiss': (np.float64(4.0), nan),
 'Brian_Lumley': (np.float64(3.0), nan),
 'Brian_Patrick_McKinley': (np.float64(4.0), nan),
 'Brian_Selznick': (np.float64(4.0), 0.0),
 'Brigid_Kemmerer': (np.float64(4.0), 0.0),
 'Brodi_Ashton': (np.float64(3.0), nan),
 'Brom': (np.float64(4.0), nan),
 'Brother_Andrew': (np.float64(4.0), nan),
 'Brother_Lawrence': (np.float64(4.0), nan),
 'Bruce_Campbell': (np.float64(4.0), nan),
 'Bruno_Schulz': (np.float64(4.0), nan),
 'Bryan_Davis': (np.float64(4.0), nan),
 'Bryan_Lee_O_Malley': (np.float64(4.0), 0.0),
 'Bryce_Courtenay': (np.float64(3.75), 0.5),
 'CLAMP': (np.float64(4.0), nan),
 'C_C_Humphreys': (np.float64(3.0), nan),
 'C_C_Hunter': (np.float64(4.0), 0.0),
 'C_D_Payne': (np.float64(4.0), nan),
 'C_E_Kilgore': (np.float64(3.0), nan),
 'C_G_Jung': (np.float64(4.0), nan),
 'C_J_Box': (np.float64(3.0), nan),
 'C_J_Daugherty': (np.float64(4.0), 0.0),
 'C_J_Redwine': (np.float64(3.0), nan),
 'C_J_Roberts': (np.float64(4.0), 0.0),
 'C_J_Sansom': (np.float64(4.0), nan),
 'C_L_Stone': (np.float64(4.0), 0.0),
 'C_L_Wilson': (np.float64(4.0), 0.0),
 'C_S_Lewis': (np.float64(3.611111111111111), 0.5016313257045503),
 'Caleb_Carr': (np.float64(4.0), nan),
 'Candace_Bushnell': (np.float64(3.0), nan),
 'Candice_Millard': (np.float64(4.0), nan),
 'Cao_Xueqin': (np.float64(4.0), nan),
 'Cara_Lynn_Shultz': (np.float64(3.0), nan),
 'Caragh_M_O_Brien': (np.float64(3.0), nan),
 'Carl_Hiaasen': (np.float64(3.0), 0.0),
 'Carl_Sagan': (np.float64(4.0), 0.0),
 'Carla_Capshaw': (np.float64(4.0), 0.0),
 'Carlo_Collodi': (np.float64(3.0), nan),
 'Carlos_Castaneda': (np.float64(3.0), nan),
 'Carlos_Rivera': (np.float64(4.0), nan),
 'Carlos_Ruiz_Zaf_n': (np.float64(3.25), 0.5),
 'Carol_E_Wyer': (np.float64(4.0), nan),
 'Carol_Plum_Ucci': (np.float64(4.0), nan),
 'Carol_Rifka_Brunt': (np.float64(4.0), nan),
 'Carol_Shields': (np.float64(3.0), nan),
 'Carole_Wilkinson': (np.float64(3.0), nan),
 'Carolina_Andujar': (np.float64(4.0), nan),
 'Caroline_B_Cooney': (np.float64(3.0), nan),
 'Carolyn_Jessop': (np.float64(3.0), nan),
 'Carolyn_Keene': (np.float64(3.0), 0.0),
 'Carolyn_Turgeon': (np.float64(3.0), nan),
 'Carrie_Jones': (np.float64(3.3333333333333335), 0.5773502691896258),
 'Carrie_Ryan': (np.float64(3.3333333333333335), 0.5773502691896258),
 'Carrie_Vaughn': (np.float64(3.0), nan),
 'Carson_McCullers': (np.float64(3.3333333333333335), 0.5773502691896258),
 'Cassandra_Clare': (np.float64(4.0), 0.0),
 'Cat_Clarke': (np.float64(3.0), 0.0),
 'Cat_Patrick': (np.float64(3.0), 0.0),
 'Cate_Tiernan': (np.float64(4.0), 0.0),
 'Cath_Crowley': (np.float64(3.0), nan),
 'Catherine_Anderson': (np.float64(4.0), 0.0),
 'Catherine_Fisher': (np.float64(3.0), 0.0),
 'Catherine_Gilbert_Murdock': (np.float64(3.0), nan),
 'Catherine_Hardwicke': (np.float64(4.0), nan),
 'Catherine_Jinks': (np.float64(3.0), nan),
 'Catherine_Marshall': (np.float64(4.0), nan),
 'Catherynne_M_Valente': (np.float64(3.6666666666666665), 0.5773502691896258),
 'Cecelia_Ahern': (np.float64(3.0), 0.0),
 'Cecily_von_Ziegesar': (np.float64(3.0), 0.0),
 'Celia_Rees': (np.float64(3.0), nan),
 'Celso_Cukierkorn': (np.float64(4.0), nan),
 'Chad_Harbach': (np.float64(3.0), nan),
 'Chaim_Potok': (np.float64(3.75), 0.5),
 'Chanda_Hahn': (np.float64(3.5), 0.7071067811865476),
 'Charlaine_Harris': (np.float64(3.5625), 0.51234753829798),
 'Charles_Baudelaire': (np.float64(4.0), 0.0),
 'Charles_Bukowski': (np.float64(3.5), 0.5477225575051661),
 'Charles_C_Mann': (np.float64(4.0), nan),
 'Charles_Darwin': (np.float64(3.0), nan),
 'Charles_Dickens': (np.float64(3.2), 0.4140393356054125),
 'Charles_Frazier': (np.float64(3.0), 0.0),
 'Charles_H_Spurgeon': (np.float64(4.0), nan),
 'Charles_M_Sheldon': (np.float64(4.0), nan),
 'Charles_Palliser': (np.float64(4.0), nan),
 'Charles_Portis': (np.float64(4.0), nan),
 'Charles_de_Lint': (np.float64(4.0), nan),
 'Charlie_Higson': (np.float64(4.0), nan),
 'Charlotte_Bront_': (np.float64(3.3333333333333335), 0.5773502691896258),
 'Charlotte_Perkins_Gilman': (np.float64(3.0), nan),
 'Chelsea_Bellingeri': (np.float64(4.0), 0.0),
 'Chelsea_Fine': (np.float64(3.0), nan),
 'Chelsea_Handler': (np.float64(3.0), 0.0),
 'Chelsea_M_Cameron': (np.float64(4.0), nan),
 'Cherie_Currie': (np.float64(3.0), nan),
 'Cherie_Priest': (np.float64(3.0), nan),
 'Cheryl_McIntyre': (np.float64(4.0), nan),
 'Cheryl_Strayed': (np.float64(3.0), nan),
 'Chetan_Bhagat': (np.float64(3.0), 0.0),
 'Chevy_Stevens': (np.float64(3.0), nan),
 'Chimamanda_Ngozi_Adichie': (np.float64(4.0), nan),
 'China_Mi_ville': (np.float64(3.25), 0.5),
 'Chinua_Achebe': (np.float64(3.0), nan),
 'Chitra_Banerjee_Divakaruni': (np.float64(3.5), 0.7071067811865476),
 'Chloe_Neill': (np.float64(4.0), 0.0),
 'Chris_Bohjalian': (np.float64(3.0), 0.0),
 'Chris_Cleave': (np.float64(3.0), nan),
 'Chris_Colfer': (np.float64(3.6666666666666665), 0.5773502691896258),
 'Chris_Crutcher': (np.float64(3.0), 0.0),
 'Chris_Kyle': (np.float64(3.0), nan),
 'Chris_Lange': (np.float64(4.0), nan),
 'Chris_Thrall': (np.float64(3.0), nan),
 'Chris_Titus': (np.float64(3.0), nan),
 'Chris_Van_Allsburg': (np.float64(4.0), nan),
 'Chris_Ware': (np.float64(4.0), nan),
 'Chris_Wooding': (np.float64(3.6666666666666665), 0.5773502691896258),
 'Chris_d_Lacey': (np.float64(3.2), 0.4472135954999579),
 'Christina_Baker_Kline': (np.float64(4.0), nan),
 'Christina_Dodd': (np.float64(4.0), nan),
 'Christina_Lauren': (np.float64(4.0), 0.0),
 'Christina_Mercer': (np.float64(4.0), nan),
 'Christina_Schwarz': (np.float64(3.0), nan),
 'Christine_Feehan': (np.float64(3.8), 0.4472135954999579),
 'Christine_M_Knight': (np.float64(4.0), 0.0),

<div class="exercise"><b>Exercise</b></div>

Lets get the best-rated book(s) for every year in our dataframe.

In [42]:
# Using .groupby, we can divide the dataframe into subsets by the values of 'year'.
# We can then iterate over these subsets
# your code here

# group the dataframe by year
for year, group in df.groupby('year'):

    best_rating = group['rating'].max()

    # filter the group to get the book with that rating
    best_books = group[group['rating'] == best_rating]

    # print year and book
    print(f"Year: {year}")
    print(best_books[['name', 'rating']])

    print("-" * 40)

Year: -1500
                       name  rating
1397  The Epic of Gilgamesh       3
----------------------------------------
Year: -800
                      name  rating
245  The Iliad/The Odyssey       4
----------------------------------------
Year: -560
                name  rating
1396  Aesop's Fables       4
----------------------------------------
Year: -512
               name  rating
673  The Art of War       3
----------------------------------------
Year: -500
                  name  rating
745  The Bhagavad Gita       4
----------------------------------------
Year: -458
              name  rating
1814  The Oresteia       3
----------------------------------------
Year: -442
         name  rating
776  Antigone       3
----------------------------------------
Year: -440
               name  rating
2526  The Histories       3
----------------------------------------
Year: -431
       name  rating
1427  Medea       3
----------------------------------------
Year: -429
            name  rating
628  Oedipus Rex       3
----------------------------------------
Year: -411
                                      name  rating
2077  The History of the Peloponnesian War       3
3756                            Lysistrata       3
----------------------------------------
Year: -400
                                 name  rating
1881  The Trial and Death of Socrates       4
3132                   Complete Works       4
----------------------------------------
Year: -390
         name  rating
4474  Apology       4
----------------------------------------
Year: -380
             name  rating
454  The Republic       3
----------------------------------------
Year: -370
               name  rating
4401  The Symposium       3
----------------------------------------
Year: -360
                name  rating
5366  Five Dialogues       4
----------------------------------------
Year: -350
                        name  rating
3273  The Nicomachean Ethics       3
----------------------------------------
Year: -29
           name  rating
595  The Aeneid       3
----------------------------------------
Year: 4
                                     name  rating
4716  The Seven Spiritual Laws of Success       4
----------------------------------------
Year: 8
               name  rating
1329  Metamorphoses       4
----------------------------------------
Year: 13
                                 name  rating
1751  The Day Jesus Rode Into Croydon       3
----------------------------------------
Year: 100
                                                   name  rating
2328  The New Oxford Annotated Bible, New Revised St...       4
----------------------------------------
Year: 121
                    name  rating
4842  The Twelve Caesars       4
----------------------------------------
Year: 130
            name  rating
1859  Holy Bible       4
----------------------------------------
Year: 158
                name  rating
4533  The Golden Ass       3
----------------------------------------
Year: 174
             name  rating
1168  Meditations       4
----------------------------------------
Year: 200
                    name  rating
1621  The Garden of Eden       3
----------------------------------------
Year: 201
                 name  rating
5403  Fe Fi FOE Comes       4
----------------------------------------
Year: 213
               name  rating
2563  NaÃ¯ve. Super       3
----------------------------------------
Year: 397
             name  rating
1392  Confessions       3
----------------------------------------
Year: 632
          name  rating
300  The Quran       4
----------------------------------------
Year: 800
        name  rating
326  Beowulf       3
----------------------------------------
Year: 900
                   name  rating
568  The Arabian Nights       4
----------------------------------------
Year: 968
                                             name  rating
4952  La BÃªte humaine (Les Rougon-Macquart, #17)       4
----------------------------------------
Year: 1002
                 name  rating
2566  The Pillow Book       4
----------------------------------------
Year: 1008
                  name  rating
851  The Tale of Genji       3
----------------------------------------
Year: 1010
           name  rating
5438  Shahnameh       4
----------------------------------------
Year: 1100
                          name  rating
1652  Rubaiyat of Omar Khayyam       4
----------------------------------------
Year: 1106
           name  rating
5797  The TÃ¡in       3
----------------------------------------
Year: 1140
                   name  rating
5830  Poema de MÃ­o Cid       3
----------------------------------------
Year: 1200
                 name  rating
4690  The Poetic Edda       4
----------------------------------------
Year: 1215
                       name  rating
3310  ÙØ«ÙÙÛ ÙØ¹ÙÙÛ       4
----------------------------------------
Year: 1220
                name  rating
4053  The Prose Edda       4
----------------------------------------
Year: 1300
                         name  rating
2862  The Imitation of Christ       4
----------------------------------------
Year: 1314
                                name  rating
362  Inferno (The Divine Comedy, #1)       3
----------------------------------------
Year: 1321
                  name  rating
131  The Divine Comedy       4
----------------------------------------
Year: 1348
              name  rating
912  The Decameron       3
----------------------------------------
Year: 1386
             name  rating
4421  Auto-da-FÃ©       4
----------------------------------------
Year: 1390
                                 name  rating
166              The Canterbury Tales       3
3271  Sir Gawain and the Green Knight       3
----------------------------------------
Year: 1391
                            name  rating
5541  Keep the Aspidistra Flying       3
----------------------------------------
Year: 1485
                   name  rating
1612  Le Morte d'Arthur       3
----------------------------------------
Year: 1516
        name  rating
1691  Utopia       3
----------------------------------------
Year: 1522
                                       name  rating
2265                         Three Kingdoms       4
3893  Romance of the Three Kingdoms, Vol. 1       4
----------------------------------------
Year: 1532
                          name  rating
383                 The Prince       3
3752  Gargantua and Pantagruel       3
----------------------------------------
Year: 1572
                     name  rating
2176  The Complete Essays       4
----------------------------------------
Year: 1589
                  name  rating
5704  Titus Andronicus       3
----------------------------------------
Year: 1590
                        name  rating
773  The Taming of the Shrew       3
----------------------------------------
Year: 1592
        name  rating
3953  Monkey       4
----------------------------------------
Year: 1595
                          name  rating
160  A Midsummer Night's Dream       3
----------------------------------------
Year: 1597
                  name  rating
13    Romeo and Juliet       3
1203       Richard III       3
----------------------------------------
Year: 1599
                       name  rating
538  Much Ado About Nothing       4
----------------------------------------
Year: 1600
                        name  rating
530   The Merchant of Venice       3
2686                 Henry V       3
----------------------------------------
Year: 1601
              name  rating
488  Twelfth Night       3
----------------------------------------
Year: 1602
        name  rating
3096  Hamlet       3
----------------------------------------
Year: 1603
                     name  rating
244               Othello       3
5360  Measure for Measure       3
----------------------------------------
Year: 1604
                name  rating
2383  Doctor Faustus       3
----------------------------------------
Year: 1605
            name  rating
81   Don Quixote       3
247    King Lear       3
----------------------------------------
Year: 1606
                      name  rating
2453  Antony and Cleopatra       3
----------------------------------------
Year: 1608
            name  rating
5344  Coriolanus       3
----------------------------------------
Year: 1609
                      name  rating
796  Shakespeare's Sonnets       4
----------------------------------------
Year: 1611
            name  rating
4616  Holy Bible       4
----------------------------------------
Year: 1621
                           name  rating
5597  The Anatomy of Melancholy       4
----------------------------------------
Year: 1623
                   name  rating
282  The Complete Works       4
----------------------------------------
Year: 1635
                   name  rating
3199  La vida es sueÃ±o       3
----------------------------------------
Year: 1642
                      name  rating
4876  A Book of Five Rings       4
----------------------------------------
Year: 1667
              name  rating
253  Paradise Lost       3
----------------------------------------
Year: 1678
                       name  rating
896  The Pilgrim's Progress       3
----------------------------------------
Year: 1680
           name  rating
4791  The Divan       4
----------------------------------------
Year: 1691
                                     name  rating
3216  The Practice of the Presence of God       4
----------------------------------------
Year: 1719
                name  rating
391  Robinson Crusoe       3
----------------------------------------
Year: 1721
               name  rating
4546  Moll Flanders       3
----------------------------------------
Year: 1726
                   name  rating
314  Gulliver's Travels       3
----------------------------------------
Year: 1729
                                             name  rating
1218  A Modest Proposal and Other Satirical Works       4
----------------------------------------
Year: 1748
                                           name  rating
3787  Clarissa, or, the History of a Young Lady       3
----------------------------------------
Year: 1749
                                       name  rating
1513  The History of Tom Jones, a Foundling       3
----------------------------------------
Year: 1759
        name  rating
257  Candide       3
----------------------------------------
Year: 1767
                                                  name  rating
982  The Life and Opinions of Tristram Shandy, Gent...       3
----------------------------------------
Year: 1774
                             name  rating
909  The Sorrows of Young Werther       3
----------------------------------------
Year: 1776
                                                   name  rating
4893  The Declaration of Independence and The Consti...       4
----------------------------------------
Year: 1778
         name  rating
4992  Evelina       3
----------------------------------------
Year: 1781
                         name  rating
2536  Critique of Pure Reason       3
----------------------------------------
Year: 1782
                          name  rating
1214  Les Liaisons Dangereuses       4
----------------------------------------
Year: 1787
                                                  name  rating
1267  The Constitution of the United States of America       4
----------------------------------------
Year: 1790
                                 name  rating
5354  The Marriage of Heaven and Hell       4
----------------------------------------
Year: 1791
                          name  rating
3926  Dream of the Red Chamber       4
----------------------------------------
Year: 1794
                                     name  rating
772  Songs of Innocence and of Experience       4
----------------------------------------
Year: 1795
          name  rating
2470  The Monk       3
----------------------------------------
Year: 1798
                                 name  rating
692   The Rime of the Ancient Mariner       3
5299                  Lyrical Ballads       3
----------------------------------------
Year: 1806
                         name  rating
5172  Phenomenology of Spirit       3
----------------------------------------
Year: 1811
                       name  rating
4817  Sense and Sensibility       4
----------------------------------------
Year: 1812
                                 name  rating
842  The Complete Grimm's Fairy Tales       4
----------------------------------------
Year: 1813
                  name  rating
3  Pride and Prejudice       4
----------------------------------------
Year: 1814
               name  rating
327  Mansfield Park       3
----------------------------------------
Year: 1815
      name  rating
3911  Emma       3
----------------------------------------
Year: 1817
            name  rating
3353  Persuasion       4
----------------------------------------
Year: 1818
            name  rating
60  Frankenstein       3
----------------------------------------
Year: 1819
        name  rating
636  Ivanhoe       3
----------------------------------------
Year: 1820
                             name  rating
3304  The Legend of Sleepy Hollow       3
----------------------------------------
Year: 1823
                           name  rating
586  The Night Before Christmas       4
----------------------------------------
Year: 1824
          name  rating
2540  Don Juan       3
----------------------------------------
Year: 1825
              name  rating
923  Eugene Onegin       4
----------------------------------------
Year: 1826
                                                  name  rating
856  The Last of the Mohicans (The Leatherstocking ...       3
----------------------------------------
Year: 1830
                   name  rating
616  The Book of Mormon       4
----------------------------------------
Year: 1831
                            name  rating
389  The Hunchback of Notre-Dame       3
----------------------------------------
Year: 1832
       name  rating
4316  Faust       3
----------------------------------------
Year: 1833
        name  rating
5249  Poetry       4
----------------------------------------
Year: 1834
              name  rating
3776  PÃ¨re Goriot       3
----------------------------------------
Year: 1835
                                                   name  rating
1841                                  Lectures on Faith       4
3054                Diary of a Madman and Other Stories       4
4190  Hymns of The Church of Jesus Christ of Latter-...       4
----------------------------------------
Year: 1837
                                   name  rating
4689  A Season in Hell/The Drunken Boat       4
----------------------------------------
Year: 1839
                    name  rating
2266  A Hero of Our Time       4
----------------------------------------
Year: 1840
                                  name  rating
3532  Tales of Mystery and Imagination       4
----------------------------------------
Year: 1841
                        name  rating
2710  The Old Curiosity Shop       3
----------------------------------------
Year: 1842
                                                   name  rating
4933  The pit and the pendulum and other stories (Pe...       4
----------------------------------------
Year: 1843
                                                name  rating
155                             The Three Musketeers       4
323           The Tell-Tale Heart and Other Writings       4
3606                                  Lost Illusions       4
5962  A Christmas Carol and Other Christmas Writings       4
----------------------------------------
Year: 1844
                           name  rating
246   The Count of Monte Cristo       4
2113                  The Raven       4
----------------------------------------
Year: 1845
                          name  rating
953  The Raven and Other Poems       4
----------------------------------------
Year: 1847
         name  rating
33  Jane Eyre       4
----------------------------------------
Year: 1848
                                name  rating
2865  White Nights and Other Stories       4
----------------------------------------
Year: 1849
         name  rating
3769  The Law       4
----------------------------------------
Year: 1850
         name  rating
4444  Ishmael       4
----------------------------------------
Year: 1851
              name  rating
5047  Paris Spleen       4
----------------------------------------
Year: 1852
                  name  rating
254  Uncle Tom's Cabin       3
----------------------------------------
Year: 1853
                                           name  rating
3042  The History of Joseph Smith by His Mother       4
----------------------------------------
Year: 1854
                             name  rating
263                        Walden       3
1555                   Hard Times       3
1812  Walden & Civil Disobedience       3
----------------------------------------
Year: 1855
                name  rating
251  Leaves of Grass       4
501  North and South       4
----------------------------------------
Year: 1856
                name  rating
4327  Song of Myself       4
----------------------------------------
Year: 1857
                   name  rating
1244  Les Fleurs du Mal       4
----------------------------------------
Year: 1859
                       name  rating
43     A Tale of Two Cities       3
357   The Origin of Species       3
1838                Oblomov       3
2815             On Liberty       3
----------------------------------------
Year: 1860
                     name  rating
3730   The Man Who Laughs       4
4093  Stepping Heavenward       4
----------------------------------------
Year: 1861
                       name  rating
536  Notes from Underground       4
----------------------------------------
Year: 1862
               name  rating
14  Les MisÃ©rables       4
----------------------------------------
Year: 1863
                                                   name  rating
5013  From the Earth to the Moon (Extraordinary Voya...       3
----------------------------------------
Year: 1864
                   name  rating
1515  Our Mutual Friend       4
----------------------------------------
Year: 1865
                                                   name  rating
12    Alice's Adventures in Wonderland & Through the...       4
1377                                Wives and Daughters       4
----------------------------------------
Year: 1866
                                                   name  rating
20                                 Crime and Punishment       4
5100  Morning and Evening, Based on the English Stan...       4
----------------------------------------
Year: 1867
                                     name  rating
3078  Capital, Volume 1 (Das Kapital, #1)       4
----------------------------------------
Year: 1868
                               name  rating
91  Little Women (Little Women, #1)       4
----------------------------------------
Year: 1869
                       name  rating
272               The Idiot       4
2733          War and Peace       4
3151  An Old-Fashioned Girl       4
----------------------------------------
Year: 1870
                name  rating
1170          Demons       4
4180  Complete Works       4
4929        Ramayana       4
----------------------------------------
Year: 1871
                                                   name  rating
2875  Through the Looking-Glass, and What Alice Foun...       4
----------------------------------------
Year: 1872
            name  rating
291  Middlemarch       3
----------------------------------------
Year: 1873
                                name  rating
933  Around the World in Eighty Days       3