# Lab 4: Classification Models Part 1: Natural Language Processing and Classification Models




In this lab, we'll build a classifier for product reviews (restricted to the magazine category), like:

Excellent! I look forward to every issue. I had no idea just how much I didn't know. The letters from the subscribers are educational, too.

Label: ⭐️⭐️⭐️⭐️⭐️ (good)

My son waited and waited, it took the 6 weeks to get delivered that they said it would but when it got here he was so dissapointed, it only took him a few minutes to read it.

Label: ⭐️ (bad)

# Loading the data
First, let's load the train/test sets and take a look at the data.

Method 1: Basic File Import

If your dataset is in the same directory as your notebook, use:

In [2]:
import pandas as pd
train = pd.read_csv('reviews_train.csv')
test = pd.read_csv('reviews_test.csv')

test.sample(5)

                                                review label
87   This magazine is full of great tips, even if y...  good
389  This is the best magazine I've ever been subsc...  good
611  I paid for the subscription and I only got one...   bad
246  How can you go wrong for only $10.00. Great id...  good
144      Excellent magazine and the best price around.  good

Method 2: Load Data from Google Drive

If your dataset is stored in Google Drive, follow these steps:

In [4]:
from google.colab import drive
# Means bring the data
drive.mount('/content/drive')

Mounted at /content/drive

In [6]:
train_path = '/content/drive/MyDrive/reviews_train.csv'
test_path = '/content/drive/MyDrive/reviews_test.csv'

train1 = pd.read_csv(train_path)
test2 = pd.read_csv(test_path)

test2.sample(5)

                                                review label
662  Used mag before I recieve mag people read\nin ...   bad
491                      Excellent use of punctuation.  good
843  Doesn't work on Kindle Paperwhite 7th Generati...   bad
644  I haven't recieved a single copy so I can't re...   bad
571  Very disappointing as every turn of the page t...   bad

#Training a baseline model
There are many approaches for training a sequence classification model for text data. In this lab, we're giving you code that mirrors what you find if you look up how to [train a text classifier](https://scikit-learn.org/stable/auto_examples/text/index.html), where we'll train an SVM on tf-idf features (numeric representations of each text field based on word occurrences).

In [8]:
# Final Question: What is the dif between technovation and vectorization?

In [9]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer

from sklearn.svm import LinearSVC
from sklearn.pipeline import Pipeline

In [13]:
# Original Way
classifier1 = Pipeline([
    ('vect', TfidfVectorizer()),
    ('clf', LinearSVC())
])

classifier = classifier1.fit(train['review'], train['label'])

In [12]:
# If i don't want to use Pipeline
# Equivalent to the above block

vectorizer = TfidfVectorizer()
train_vectors = vectorizer.fit_transform(train['review'])
test_vectors = vectorizer.transform(test['review'])

classe = LinearSVC()
classe.fit(train_vectors, train['label'])

# Evaluating model accuracy

In [14]:
from sklearn import metrics
from sklearn.metrics import accuracy_score

In [15]:
def evaluate (model):
  predicted = model.predict(test['review'])
  print(metrics.classification_report(test['label'], predicted))
  print("Accuracy:", accuracy_score(test['label'], predicted))

In [18]:
evaluate(classifier)
# How many was correct: precision
# How many is predicted on the whole thing: recall
# How many instance where good and bad: support
# The overall accuracy is: Accuracy

              precision    recall  f1-score   support

         bad       0.73      0.70      0.71       500
        good       0.71      0.74      0.73       500

    accuracy                           0.72      1000
   macro avg       0.72      0.72      0.72      1000
weighted avg       0.72      0.72      0.72      1000

Accuracy: 0.72

# Trying another model
76% accuracy is not great for this binary classification problem. Can you do better with a different model, or by tuning hyperparameters for the SVM trained with SGD?

# Exercise 1

Can you train a more accurate model on the dataset (without changing the dataset)? You might find this [scikit-learn classifier comparison](https://scikit-learn.org/stable/auto_examples/classification/plot_classifier_comparison.html) handy, as well as the documentation for [supervised learning in scikit-learn](https://scikit-learn.org/stable/supervised_learning.html).

One idea for a model you could try is a [naive Bayes classifier](https://scikit-learn.org/stable/modules/generated/sklearn.naive_bayes.MultinomialNB.html).

You could also try experimenting with different values of the model hyperparameters, perhaps tuning them via a [grid search](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.GridSearchCV.html).

Or you can even try training multiple different models and [ensembling](https://scikit-learn.org/stable/modules/ensemble.html#voting-classifier) their predictions, a strategy often used to win prediction competitions like Kaggle.

Advanced: If you want to be more ambitious, you could try an even fancier model, like training a Transformer neural network. If you go with that, you'll want to fine-tune a pre-trained model. This guide from [HuggingFace](https://huggingface.co/docs/transformers/training) may be helpful.

In [20]:
from sklearn.datasets import make_circles, make_classification, make_moons
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
from sklearn.ensemble import AdaBoostClassifier, RandomForestClassifier
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.gaussian_process.kernels import RBF
from sklearn.inspection import DecisionBoundaryDisplay
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier



classifier2 = Pipeline([
    ('vect', TfidfVectorizer()),
    ('clf', KNeighborsClassifier())
])

classifier2 = classifier2.fit(train['review'], train['label'])
evaluate(classifier2)

              precision    recall  f1-score   support

         bad       0.81      0.77      0.79       500
        good       0.78      0.82      0.80       500

    accuracy                           0.79      1000
   macro avg       0.79      0.79      0.79      1000
weighted avg       0.79      0.79      0.79      1000

Accuracy: 0.791

In [22]:
classifier3 = Pipeline([
    ('vect', TfidfVectorizer()),
    ('clf', AdaBoostClassifier())
])

classifier3 = classifier3.fit(train['review'], train['label'])
evaluate(classifier3)

              precision    recall  f1-score   support

         bad       0.88      0.51      0.64       500
        good       0.65      0.93      0.77       500

    accuracy                           0.72      1000
   macro avg       0.77      0.72      0.71      1000
weighted avg       0.77      0.72      0.71      1000

Accuracy: 0.719

In [23]:
classifier4 = Pipeline([
    ('vect', TfidfVectorizer()),
    ('clf', RandomForestClassifier())
])

classifier4 = classifier4.fit(train['review'], train['label'])
evaluate(classifier4)

              precision    recall  f1-score   support

         bad       0.82      0.89      0.85       500
        good       0.88      0.80      0.84       500

    accuracy                           0.85      1000
   macro avg       0.85      0.85      0.85      1000
weighted avg       0.85      0.85      0.85      1000

Accuracy: 0.846

In [26]:
classifier5 = Pipeline([
    ('vect', TfidfVectorizer()),
    ('clf', MLPClassifier())
])

classifier5 = classifier5.fit(train['review'], train['label'])
evaluate(classifier5)

              precision    recall  f1-score   support

         bad       0.73      0.75      0.74       500
        good       0.75      0.72      0.73       500

    accuracy                           0.74      1000
   macro avg       0.74      0.74      0.74      1000
weighted avg       0.74      0.74      0.74      1000

Accuracy: 0.738

/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:698: UserWarning: Training interrupted by user.
  warnings.warn("Training interrupted by user.")

In [27]:
classifier6 = Pipeline([
    ('vect', TfidfVectorizer()),
    ('clf', DecisionTreeClassifier())
])

classifier6 = classifier6.fit(train['review'], train['label'])
evaluate(classifier6)

              precision    recall  f1-score   support

         bad       0.78      0.78      0.78       500
        good       0.78      0.78      0.78       500

    accuracy                           0.78      1000
   macro avg       0.78      0.78      0.78      1000
weighted avg       0.78      0.78      0.78      1000

Accuracy: 0.779

In [30]:
# So the best classifier is the Random Forest Classifier with an accuracy of 0.846

In [ ]:
# YOUR CODE HERE

# evaluate your model and see if it does better
# than the ones we provided

In [ ]:
#Try all models in  scikit-learn classifier comparison

In [ ]:
# AND try training multiple different models and ensembling their predictions

from transformers import pipeline

# Load a pre-trained text classification model
classifier = pipeline("text-classification", model="nlptown/bert-base-multilingual-uncased-sentiment")

# Predict on a sample review
sample_text = test['review'].iloc[0]
print(classifier(sample_text))

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json:   0%|          | 0.00/953 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/669M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/39.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/872k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

Device set to use cpu

[{'label': '5 stars', 'score': 0.7051732540130615}]

Taking a closer look at the training data
Let's actually take a look at some of the training data:

#Exercise 2
Take a look at some more examples in the dataset. Do you notice any patterns with bad data points?